name: Submodule Update

#############################
# Start the job on all push #
#############################
on:
  push

###############
# Set the Job #
###############
jobs:
  update-submodule:
    strategy:
      matrix:
        repository: ['Pauls-Printers/hevo-config', 'Pauls-Printers/mz2-config']
    runs-on: ubuntu-latest
    steps:
      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        uses: PaulRitter/github-action-create-commit-parent-submodule@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          parent_repository: ${{ matrix.repository }}
          parent_branch: master